In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)


In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f" Ones type {x_ones} \n Rand type {x_rand}")

 Ones type tensor([[1, 1],
        [1, 1]]) 
 Rand type tensor([[0.3027, 0.5892],
        [0.2444, 0.6007]])


In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Tensor : \n {rand_tensor}\n")
print(f"Tensor : \n {ones_tensor}\n")
print(f"Tensor : \n {zeros_tensor}\n")

Tensor : 
 tensor([[0.9946, 0.8998, 0.3203],
        [0.4439, 0.6323, 0.3367]])

Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [16]:
# Tensor Attribute - shape, dattatype, device

# 텐서 저장을 gpu에할지 cpu에할지 정함
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
tensor = torch.rand(3,4)
print(f"Shape of tensor : {tensor.shape}")
print(f"Dtype of tensor : {tensor.dtype}")
print(f"Device of tensor : {tensor.device}")

# tensor2는 gpu에 저장
tensor2 = torch.rand(3,4,device = device)
print(f"Device of tensor2 : {tensor2.device}")

#tensor1을 mps로 이동
if torch.backends.mps.is_available():
    tensor = tensor.to("mps")
print(f"Device of tensor : {tensor.device}")



Shape of tensor : torch.Size([3, 4])
Dtype of tensor : torch.float32
Device of tensor : cpu
Device of tensor2 : mps:0
Device of tensor : mps:0


In [25]:
# tensor operate
tensor = torch.ones(4,4)
print(f"First row : {tensor[0]}")
print(f"First column : {tensor[:,0]}")
print(f"Last column : {tensor[...,-1]}")
print(f"Last column : {tensor[:,-1]}")

tensor[-1,:] = 0
print(tensor)
tensor[:,1] = 0
print(tensor)



First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])


In [34]:
# 1개의 행렬옆에 열방향으로 추가함
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)
# 행방향으로 각 행렬이 개별적으로 추가됨
t2 = torch.stack([tensor, tensor, tensor])
print(t2)
t3 = torch.stack([tensor, tensor,tensor,tensor], dim = 2)
print(t3)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [0., 0., 0., 0.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [0., 0., 0., 0.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]

In [38]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1) # rand_like 는 shape를 똑같이 맞춰서 랜덤숫자로채워서만들어줌
torch.matmul(tensor, tensor.T, out=y3)
print(f"y1 : \n {y1} \n y2 : \n {y2} \n y3 : \n {y3}")

# element multiply

z1 = tensor*tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)
print("element multiply : ")
print(z3)


y1 : 
 tensor([[3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [0., 0., 0., 0.]]) 
 y2 : 
 tensor([[3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [0., 0., 0., 0.]]) 
 y3 : 
 tensor([[3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [3., 3., 3., 0.],
        [0., 0., 0., 0.]])
element multiply : 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])


In [43]:
agg = tensor.sum()
print(f"agg type {agg.dtype}")
agg_item = agg.item()
print(f"agg_item type : {type(agg_item)}")
print(agg_item, type(agg_item), agg_item)

agg type torch.float32
agg_item type : <class 'float'>
9.0 <class 'float'> 9.0


In [44]:
print(f"{tensor} \n")
# 바꿔치기연산 -> cpp에서 +=, -=, *= 등의 역할과 같음
# 기록이 삭제되어 도함수계산에 문제발생 -> 권장하지 않음
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [5., 5., 5., 5.]])


In [45]:
# tesnor 와 np배열은 메모리 공유 -> 서로 변경사항이 반영됨
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t : {t}")
print(f"n : {n}")

t.add_(1)
print(f"n after t.add_(1) : {n}")

t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n : [1. 1. 1. 1. 1.]
n after t.add_(1) : [2. 2. 2. 2. 2.]
