In [1]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
b = torch.randn(3,requires_grad = True)
w = torch.randn(5,3,requires_grad = True)
z = torch.matmul(x,w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [2]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")


Gradient function for z = <AddBackward0 object at 0x13aa67310>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x13aa67040>


In [3]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0166, 0.0507, 0.3115],
        [0.0166, 0.0507, 0.3115],
        [0.0166, 0.0507, 0.3115],
        [0.0166, 0.0507, 0.3115],
        [0.0166, 0.0507, 0.3115]])
tensor([0.0166, 0.0507, 0.3115])


In [10]:
z = torch.matmul(x,w)+b
z2 = torch.matmul(x,w)+b
print(z2.requires_grad)
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x,w)+b

# 파라미터 고정, 역전파생략으로 계산효율 상향
z2_det = z2.detach()
print(z2_det.requires_grad)
print(z.requires_grad)

True
True
False
False


In [11]:
# 출력함수가 임의의 텐서인경우 자코비안행렬로 아웃풋이 주어짐
inp = torch.eye(4,5,requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"Firsh call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

Firsh call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
